// Icon Constants for NexChat Application
// This file centralizes all icon usage to ensure consistency across the application

import {
  // Navigation Icons
  Home,
  ArrowLeft,
  ArrowRight,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  
  // Chat Icons
  MessageSquare,
  Phone,
  Video,
  Search,
  MoreVertical,
  MoreHorizontal,
  
  // File Icons
  File,
  ImageIcon,
  Video as VideoIcon,
  Music,
  FileText,
  Upload,
  Download,
  Paperclip,
  
  // User Icons
  User,
  Users,
  UserPlus,
  Crown,
  Settings,
  
  // Action Icons
  Edit,
  Edit2,
  Trash2,
  Reply,
  Star,
  Share2,
  Copy,
  Plus,
  Minus,
  
  // Status Icons
  Circle,
  Clock,
  XCircle,
  CheckCircle,
  
  // Notification Icons
  Bell,
  BellOff,
  Volume2,
  VolumeX,
  
  // Theme Icons
  Sun,
  Moon,
  Monitor,
  
  // Security Icons
  Shield,
  Lock,
  Eye,
  EyeOff,
  
  // Communication Icons
  Mic,
  MicOff,
  Send,
  Smile,
  
  // Media Icons
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  
  // Utility Icons
  Camera,
  MapPin,
  Link,
  ExternalLink,
  Heart,
  Bookmark,
  Archive,
  Pin,
  LogOut,
  Save,
  RefreshCw,
  Loader2,
  AlertCircle,
  Check,
  Info,
  HelpCircle,
  Grid,
  List,
  Filter,
  SortAsc,
  SortDesc,
  Calendar,
  Clock as ClockIcon,
  Mail,
  Phone as PhoneIcon,
  Globe,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Signal,
  SignalHigh,
  SignalMedium,
  SignalLow,
  SignalZero,
  
  // Creative Icons
  Sparkles,
  Wand2,
  Palette,
  Brush,
  Layers,
  LayoutGrid,
  PanelLeft,
  PanelRight,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  Maximize,
  Minimize,
  Move,
  RotateCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Crop,
  Scissors,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List as ListIcon,
  ListOrdered,
  Quote,
  Code as CodeIcon,
  Hash,
  AtSign,
  DollarSign,
  Percent,
  Hash as HashIcon,
  Infinity,
  Target,
  Zap,
  Flame,
  Droplets,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Sun as SunIcon,
  Moon as MoonIcon,
  Star as StarIcon,
  Planet,
  Rocket,
  Satellite,
  Telescope,
  Microscope,
  Flask,
  TestTube,
  Beaker,
  Atom,
  DNA,
  Brain,
  Heart as HeartIcon,
  Lungs,
  Stomach,
  Bone,
  Pill,
  Syringe,
  Thermometer,
  Stethoscope,
  Activity,
  TrendingUp,
  TrendingDown,
  BarChart,
  BarChart3,
  LineChart,
  PieChart,
  DonutChart,
  ScatterChart,
  AreaChart,
  CandlestickChart,
  Radar,
  Gauge,
  Timer,
  Stopwatch,
  Hourglass,
  Calendar as CalendarIcon,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  CalendarMinus,
  CalendarRange,
  CalendarClock,
  CalendarHeart,
  CalendarStar,
  CalendarUser,
  CalendarSearch,
  CalendarEdit,
  CalendarTrash,
  CalendarOff,
  CalendarRepeat,
  CalendarRepeat1,
  CalendarRepeat2,
  CalendarRepeat3,
  CalendarRepeat4,
  CalendarRepeat5,
  CalendarRepeat6,
  CalendarRepeat7,
  CalendarRepeat8,
  CalendarRepeat9,
  CalendarRepeat10,
  CalendarRepeat11,
  CalendarRepeat12,
  CalendarRepeat13,
  CalendarRepeat14,
  CalendarRepeat15,
  CalendarRepeat16,
  CalendarRepeat17,
  CalendarRepeat18,
  CalendarRepeat19,
  CalendarRepeat20,
  CalendarRepeat21,
  CalendarRepeat22,
  CalendarRepeat23,
  CalendarRepeat24,
  CalendarRepeat25,
  CalendarRepeat26,
  CalendarRepeat27,
  CalendarRepeat28,
  CalendarRepeat29,
  CalendarRepeat30,
  CalendarRepeat31,
  CalendarRepeat32,
  CalendarRepeat33,
  CalendarRepeat34,
  CalendarRepeat35,
  CalendarRepeat36,
  CalendarRepeat37,
  CalendarRepeat38,
  CalendarRepeat39,
  CalendarRepeat40,
  CalendarRepeat41,
  CalendarRepeat42,
  CalendarRepeat43,
  CalendarRepeat44,
  CalendarRepeat45,
  CalendarRepeat46,
  CalendarRepeat47,
  CalendarRepeat48,
  CalendarRepeat49,
  CalendarRepeat50,
  CalendarRepeat51,
  CalendarRepeat52,
  CalendarRepeat53,
  CalendarRepeat54,
  CalendarRepeat55,
  CalendarRepeat56,
  CalendarRepeat57,
  CalendarRepeat58,
  CalendarRepeat59,
  CalendarRepeat60,
  CalendarRepeat61,
  CalendarRepeat62,
  CalendarRepeat63,
  CalendarRepeat64,
  CalendarRepeat65,
  CalendarRepeat66,
  CalendarRepeat67,
  CalendarRepeat68,
  CalendarRepeat69,
  CalendarRepeat70,
  CalendarRepeat71,
  CalendarRepeat72,
  CalendarRepeat73,
  CalendarRepeat74,
  CalendarRepeat75,
  CalendarRepeat76,
  CalendarRepeat77,
  CalendarRepeat78,
  CalendarRepeat79,
  CalendarRepeat80,
  CalendarRepeat81,
  CalendarRepeat82,
  CalendarRepeat83,
  CalendarRepeat84,
  CalendarRepeat85,
  CalendarRepeat86,
  CalendarRepeat87,
  CalendarRepeat88,
  CalendarRepeat89,
  CalendarRepeat90,
  CalendarRepeat91,
  CalendarRepeat92,
  CalendarRepeat93,
  CalendarRepeat94,
  CalendarRepeat95,
  CalendarRepeat96,
  CalendarRepeat97,
  CalendarRepeat98,
  CalendarRepeat99,
  CalendarRepeat100,
} from 'lucide-react'

// Icon Categories
export const ICONS = {
  // Navigation Icons
  NAVIGATION: {
    HOME: Home,
    BACK: ArrowLeft,
    FORWARD: ArrowRight,
    MENU: Menu,
    CLOSE: X,
    CHEVRON_DOWN: ChevronDown,
    CHEVRON_UP: ChevronUp,
    CHEVRON_LEFT: ChevronLeft,
    CHEVRON_RIGHT: ChevronRight,
  },

  // Chat Icons
  CHAT: {
    MESSAGE: MessageSquare,
    PHONE: Phone,
    VIDEO: Video,
    SEARCH: Search,
    MORE_VERTICAL: MoreVertical,
    MORE_HORIZONTAL: MoreHorizontal,
  },

  // File Icons
  FILE: {
    FILE: File,
    IMAGE: ImageIcon,
    VIDEO: VideoIcon,
    AUDIO: Music,
    DOCUMENT: FileText,
    UPLOAD: Upload,
    DOWNLOAD: Download,
    ATTACHMENT: Paperclip,
  },

  // User Icons
  USER: {
    USER: User,
    USERS: Users,
    USER_PLUS: UserPlus,
    CROWN: Crown,
    SETTINGS: Settings,
  },

  // Action Icons
  ACTION: {
    EDIT: Edit,
    EDIT_2: Edit2,
    DELETE: Trash2,
    REPLY: Reply,
    STAR: Star,
    SHARE: Share2,
    COPY: Copy,
    PLUS: Plus,
    MINUS: Minus,
  },

  // Status Icons
  STATUS: {
    ONLINE: Circle,
    AWAY: Clock,
    BUSY: XCircle,
    COMPLETED: CheckCircle,
  },

  // Notification Icons
  NOTIFICATION: {
    BELL: Bell,
    BELL_OFF: BellOff,
    VOLUME: Volume2,
    VOLUME_OFF: VolumeX,
  },

  // Theme Icons
  THEME: {
    SUN: Sun,
    MOON: Moon,
    MONITOR: Monitor,
  },

  // Security Icons
  SECURITY: {
    SHIELD: Shield,
    LOCK: Lock,
    EYE: Eye,
    EYE_OFF: EyeOff,
  },

  // Communication Icons
  COMMUNICATION: {
    MIC: Mic,
    MIC_OFF: MicOff,
    SEND: Send,
    SMILE: Smile,
  },

  // Media Icons
  MEDIA: {
    PLAY: Play,
    PAUSE: Pause,
    STOP: Square,
    SKIP_BACK: SkipBack,
    SKIP_FORWARD: SkipForward,
  },

  // Utility Icons
  UTILITY: {
    CAMERA: Camera,
    LOCATION: MapPin,
    LINK: Link,
    EXTERNAL_LINK: ExternalLink,
    HEART: Heart,
    BOOKMARK: Bookmark,
    ARCHIVE: Archive,
    PIN: Pin,
    LOGOUT: LogOut,
    SAVE: Save,
    REFRESH: RefreshCw,
    LOADER: Loader2,
    ALERT: AlertCircle,
    CHECK: Check,
    INFO: Info,
    HELP: HelpCircle,
    GRID: Grid,
    LIST: List,
    FILTER: Filter,
    SORT_ASC: SortAsc,
    SORT_DESC: SortDesc,
  },

  // Creative Icons
  CREATIVE: {
    SPARKLES: Sparkles,
    WAND: Wand2,
    PALETTE: Palette,
    BRUSH: Brush,
    LAYERS: Layers,
    LAYOUT_GRID: LayoutGrid,
    PANEL_LEFT: PanelLeft,
    PANEL_RIGHT: PanelRight,
    SIDEBAR: Sidebar,
    SIDEBAR_CLOSE: SidebarClose,
    SIDEBAR_OPEN: SidebarOpen,
    MAXIMIZE: Maximize,
    MINIMIZE: Minimize,
    MOVE: Move,
    ROTATE_CW: RotateCw,
    ROTATE_CCW: RotateCcw,
    ZOOM_IN: ZoomIn,
    ZOOM_OUT: ZoomOut,
    CROP: Crop,
    SCISSORS: Scissors,
    TYPE: Type,
    BOLD: Bold,
    ITALIC: Italic,
    UNDERLINE: Underline,
    STRIKETHROUGH: Strikethrough,
    ALIGN_LEFT: AlignLeft,
    ALIGN_CENTER: AlignCenter,
    ALIGN_RIGHT: AlignRight,
    ALIGN_JUSTIFY: AlignJustify,
    LIST_ICON: ListIcon,
    LIST_ORDERED: ListOrdered,
    QUOTE: Quote,
    CODE: CodeIcon,
    HASH: Hash,
    AT_SIGN: AtSign,
    DOLLAR: DollarSign,
    PERCENT: Percent,
    INFINITY: Infinity,
    TARGET: Target,
    ZAP: Zap,
    FLAME: Flame,
    DROPLETS: Droplets,
    CLOUD: Cloud,
    CLOUD_RAIN: CloudRain,
    CLOUD_SNOW: CloudSnow,
    CLOUD_LIGHTNING: CloudLightning,
    SUN_ICON: SunIcon,
    MOON_ICON: MoonIcon,
    STAR_ICON: StarIcon,
    PLANET: Planet,
    ROCKET: Rocket,
    SATELLITE: Satellite,
    TELESCOPE: Telescope,
    MICROSCOPE: Microscope,
    FLASK: Flask,
    TEST_TUBE: TestTube,
    BEAKER: Beaker,
    ATOM: Atom,
    DNA: DNA,
    BRAIN: Brain,
    HEART_ICON: HeartIcon,
    LUNGS: Lungs,
    STOMACH: Stomach,
    BONE: Bone,
    PILL: Pill,
    SYRINGE: Syringe,
    THERMOMETER: Thermometer,
    STETHOSCOPE: Stethoscope,
    ACTIVITY: Activity,
    TRENDING_UP: TrendingUp,
    TRENDING_DOWN: TrendingDown,
    BAR_CHART: BarChart,
    BAR_CHART_3: BarChart3,
    LINE_CHART: LineChart,
    PIE_CHART: PieChart,
    DONUT_CHART: DonutChart,
    SCATTER_CHART: ScatterChart,
    AREA_CHART: AreaChart,
    CANDLESTICK_CHART: CandlestickChart,
    RADAR: Radar,
    GAUGE: Gauge,
    TIMER: Timer,
    STOPWATCH: Stopwatch,
    HOURGLASS: Hourglass,
  },
} as const

// Icon Size Constants
export const ICON_SIZES = {
  XS: 'h-3 w-3',
  SM: 'h-4 w-4',
  MD: 'h-5 w-5',
  LG: 'h-6 w-6',
  XL: 'h-8 w-8',
  '2XL': 'h-10 w-10',
  '3XL': 'h-12 w-12',
} as const

// Icon Color Classes
export const ICON_COLORS = {
  PRIMARY: 'text-primary',
  SECONDARY: 'text-secondary-foreground',
  MUTED: 'text-muted-foreground',
  DESTRUCTIVE: 'text-destructive',
  SUCCESS: 'text-green-600',
  WARNING: 'text-yellow-600',
  INFO: 'text-blue-600',
  WHITE: 'text-white',
  BLACK: 'text-black',
} as const

// Icon Variants
export const ICON_VARIANTS = {
  DEFAULT: 'text-foreground',
  PRIMARY: 'text-primary',
  SECONDARY: 'text-secondary-foreground',
  MUTED: 'text-muted-foreground',
  DESTRUCTIVE: 'text-destructive',
  SUCCESS: 'text-green-600',
  WARNING: 'text-yellow-600',
  INFO: 'text-blue-600',
} as const

// Helper function to get icon component
export function getIcon(category: keyof typeof ICONS, name: string) {
  const iconCategory = ICONS[category]
  if (!iconCategory) {
    console.warn(`Icon category "${category}" not found`)
    return null
  }
  
  const icon = iconCategory[name as keyof typeof iconCategory]
  if (!icon) {
    console.warn(`Icon "${name}" not found in category "${category}"`)
    return null
  }
  
  return icon
}

// Helper function to get icon with size and color
export function getIconWithProps(
  category: keyof typeof ICONS,
  name: string,
  size: keyof typeof ICON_SIZES = 'MD',
  color: keyof typeof ICON_COLORS = 'PRIMARY',
  className?: string
) {
  const IconComponent = getIcon(category, name)
  if (!IconComponent) return null
  
  return {
    component: IconComponent,
    className: `${ICON_SIZES[size]} ${ICON_COLORS[color]} ${className || ''}`
  }
}

// Type definitions
export type IconCategory = keyof typeof ICONS
export type IconName<T extends IconCategory> = keyof typeof ICONS[T]
export type IconSize = keyof typeof ICON_SIZES
export type IconColor = keyof typeof ICON_COLORS
export type IconVariant = keyof typeof ICON_VARIANTS 