import type { Chat, Message, User } from "./types"

export const mockUsers: User[] = [
  {
    id: "user1",
    name: "Sarah Johnson",
    avatar: "/placeholder.svg?height=40&width=40&text=SJ",
    isOnline: true,
    about: "Living life one day at a time ✨",
  },
  {
    id: "user2",
    name: "Michael Chen",
    avatar: "/placeholder.svg?height=40&width=40&text=MC",
    isOnline: false,
    about: "Photography enthusiast and coffee lover",
  },
  {
    id: "user3",
    name: "Emma Wilson",
    avatar: "/placeholder.svg?height=40&width=40&text=EW",
    isOnline: true,
    about: "Travel | Food | Adventure",
  },
  {
    id: "user4",
    name: "James Rodriguez",
    avatar: "/placeholder.svg?height=40&width=40&text=JR",
    isOnline: false,
  },
  {
    id: "user5",
    name: "Olivia Taylor",
    avatar: "/placeholder.svg?height=40&width=40&text=OT",
    isOnline: true,
    about: "Digital artist and web designer",
  },
  {
    id: "user6",
    name: "Design Team",
    avatar: "/placeholder.svg?height=40&width=40&text=DT",
    isOnline: false,
    about: "Group for design discussions and feedback",
  },
  {
    id: "user7",
    name: "Project Alpha",
    avatar: "/placeholder.svg?height=40&width=40&text=PA",
    isOnline: true,
    about: "Coordination for Project Alpha development",
  },
]

export const mockChats: Chat[] = [
  {
    id: "chat1",
    user: mockUsers[0],
    lastMessage: "Are we still meeting tomorrow?",
    time: "10:42 AM",
    unread: 2,
    typing: true,
  },
  {
    id: "chat2",
    user: mockUsers[1],
    lastMessage: "I'll send you the photos later",
    time: "Yesterday",
    unread: 0,
  },
  {
    id: "chat3",
    user: mockUsers[2],
    lastMessage: "The presentation went well!",
    time: "Yesterday",
    unread: 0,
  },
  {
    id: "chat4",
    user: mockUsers[3],
    lastMessage: "Can you review the document?",
    time: "Monday",
    unread: 0,
  },
  {
    id: "chat5",
    user: mockUsers[4],
    lastMessage: "Thanks for your help!",
    time: "Monday",
    unread: 0,
  },
  {
    id: "chat6",
    user: mockUsers[5],
    lastMessage: "Alex: Updated the logo design",
    time: "Sunday",
    unread: 3,
    isGroup: true,
  },
  {
    id: "chat7",
    user: mockUsers[6],
    lastMessage: "Maria: Let's schedule a call",
    time: "Last week",
    unread: 0,
    isGroup: true,
  },
]

export const mockMessages: Record<string, Message[]> = {
  chat1: [
    {
      id: "msg1",
      content: "Hey Sarah, how are you doing?",
      timestamp: "2023-06-13T10:30:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg2",
      content: "Hi! I'm good, thanks for asking. Just finishing up some work. How about you?",
      timestamp: "2023-06-13T10:32:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg3",
      content: "I'm doing well! Just planning for the upcoming project.",
      timestamp: "2023-06-13T10:33:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg4",
      content: "That sounds great! Are we still meeting tomorrow to discuss the details?",
      timestamp: "2023-06-13T10:35:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg5",
      content: "Yes, definitely. Let's meet at the coffee shop at 10 AM. Does that work for you?",
      timestamp: "2023-06-13T10:36:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg6",
      content: "Perfect! I'll see you there. I have some new ideas to share.",
      timestamp: "2023-06-13T10:38:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg7",
      content: "Looking forward to it! Don't forget to bring the design mockups.",
      timestamp: "2023-06-13T10:40:00Z",
      sender: "me",
      status: "read",
    },
  ],
  chat2: [
    {
      id: "msg1",
      content: "Hey Michael, did you take photos at the event yesterday?",
      timestamp: "2023-06-12T14:20:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg2",
      content: "Yes, I got some great shots! The lighting was perfect.",
      timestamp: "2023-06-12T14:25:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg3",
      content: "Awesome! Can you share them with me?",
      timestamp: "2023-06-12T14:26:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg4",
      content: "Sure thing. I need to edit them first. I'll send you the photos later today.",
      timestamp: "2023-06-12T14:30:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg5",
      content: "Thanks! I appreciate it.",
      timestamp: "2023-06-12T14:31:00Z",
      sender: "me",
      status: "read",
    },
  ],
  chat3: [
    {
      id: "msg1",
      content: "Good luck with your presentation today!",
      timestamp: "2023-06-12T09:00:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg2",
      content: "Thanks! I'm a bit nervous but prepared.",
      timestamp: "2023-06-12T09:05:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg3",
      content: "You'll do great! Let me know how it goes.",
      timestamp: "2023-06-12T09:06:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg4",
      content: "Just finished! The presentation went well! They loved the new concept.",
      timestamp: "2023-06-12T11:30:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg5",
      content: "That's fantastic news! Congratulations! 🎉",
      timestamp: "2023-06-12T11:32:00Z",
      sender: "me",
      status: "read",
    },
  ],
  chat4: [
    {
      id: "msg1",
      content: "Hi James, I've sent you the quarterly report.",
      timestamp: "2023-06-10T13:15:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg2",
      content: "Got it, thanks! I'll take a look.",
      timestamp: "2023-06-10T13:20:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg3",
      content: "Can you review the document when you have time? I need your feedback by Friday.",
      timestamp: "2023-06-10T15:45:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg4",
      content: "Sure, I'll review it tomorrow and get back to you.",
      timestamp: "2023-06-10T16:00:00Z",
      sender: "me",
      status: "read",
    },
  ],
  chat5: [
    {
      id: "msg1",
      content: "Olivia, do you have a moment to help me with the design?",
      timestamp: "2023-06-10T10:00:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg2",
      content: "Sure, what do you need help with?",
      timestamp: "2023-06-10T10:05:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg3",
      content: "I'm trying to create a gradient background but it's not looking right.",
      timestamp: "2023-06-10T10:07:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg4",
      content: "I can help with that. Try using these color codes: #3494E6 and #EC6EAD with a 45-degree angle.",
      timestamp: "2023-06-10T10:10:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg5",
      content: "That worked perfectly! Thanks for your help!",
      timestamp: "2023-06-10T10:15:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg6",
      content: "You're welcome! Let me know if you need anything else.",
      timestamp: "2023-06-10T10:16:00Z",
      sender: "other",
      status: "read",
    },
  ],
  chat6: [
    {
      id: "msg1",
      content: "Hello everyone! I've created a new channel for our design team.",
      timestamp: "2023-06-09T09:00:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg2",
      content: "Great idea! This will help us stay organized.",
      timestamp: "2023-06-09T09:05:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg3",
      content: "I've uploaded the brand guidelines to the shared folder.",
      timestamp: "2023-06-09T09:10:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg4",
      content: "Thanks! I'll review them today.",
      timestamp: "2023-06-09T09:15:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg5",
      content: "I've updated the logo design based on the client's feedback. Check it out!",
      timestamp: "2023-06-09T14:30:00Z",
      sender: "other",
      status: "read",
    },
  ],
  chat7: [
    {
      id: "msg1",
      content: "Welcome to Project Alpha! This is where we'll coordinate our development efforts.",
      timestamp: "2023-06-05T10:00:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg2",
      content: "Thanks for setting this up! I'm excited to get started.",
      timestamp: "2023-06-05T10:05:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg3",
      content: "I've shared the project roadmap in the documents section.",
      timestamp: "2023-06-05T10:10:00Z",
      sender: "me",
      status: "read",
    },
    {
      id: "msg4",
      content: "Let's schedule a call to discuss the initial requirements.",
      timestamp: "2023-06-05T10:30:00Z",
      sender: "other",
      status: "read",
    },
    {
      id: "msg5",
      content: "Good idea. How about tomorrow at 2 PM?",
      timestamp: "2023-06-05T10:35:00Z",
      sender: "me",
      status: "read",
    },
  ],
}
